version: '3.8'
services:
  server-registry:
    build: server-registry/
    ports:
      - "8761:8761"
  api:
    build: api/
    depends_on:
      - server-registry
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://server-registry:8761/eureka"}}}}'
    ports:
      - "8081:8081"
  client:
    build: client/
    depends_on:
      - api
      - server-registry
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://server-registry:8761/eureka"}}}}'
    ports:
      - "8080:8080"